// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data-server.proto

package com.nokia.sample.model;

public final class DataServer {
  private DataServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *required int32 id = 1 [default = 0]; in proto2
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     *Unique numbered tag 						//optional string value = 2; in proto2
     * </pre>
     *
     * <code>optional string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <pre>
     *Unique numbered tag 						//optional string value = 2; in proto2
     * </pre>
     *
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>repeated string messageType = 3;</code>
     */
    java.util.List<java.lang.String>
        getMessageTypeList();
    /**
     * <code>repeated string messageType = 3;</code>
     */
    int getMessageTypeCount();
    /**
     * <code>repeated string messageType = 3;</code>
     */
    java.lang.String getMessageType(int index);
    /**
     * <code>repeated string messageType = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageTypeBytes(int index);

    /**
     * <pre>
     *optional Corpus corpus = 4 [default = UNIVERSAL]; in proto2
     * </pre>
     *
     * <code>optional .Data.Corpus corpus = 4;</code>
     */
    int getCorpusValue();
    /**
     * <pre>
     *optional Corpus corpus = 4 [default = UNIVERSAL]; in proto2
     * </pre>
     *
     * <code>optional .Data.Corpus corpus = 4;</code>
     */
    com.nokia.sample.model.DataServer.Data.Corpus getCorpus();
  }
  /**
   * Protobuf type {@code Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Data)
      DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      id_ = 0;
      value_ = "";
      messageType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      corpus_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                messageType_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              messageType_.add(s);
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              corpus_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          messageType_ = messageType_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nokia.sample.model.DataServer.internal_static_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nokia.sample.model.DataServer.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nokia.sample.model.DataServer.Data.class, com.nokia.sample.model.DataServer.Data.Builder.class);
    }

    /**
     * Protobuf enum {@code Data.Corpus}
     */
    public enum Corpus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNIVERSAL = 0;</code>
       */
      UNIVERSAL(0),
      /**
       * <code>WEB = 1;</code>
       */
      WEB(1),
      /**
       * <code>IMAGES = 2;</code>
       */
      IMAGES(2),
      /**
       * <code>LOCAL = 3;</code>
       */
      LOCAL(3),
      /**
       * <code>NEWS = 4;</code>
       */
      NEWS(4),
      /**
       * <code>PRODUCTS = 5;</code>
       */
      PRODUCTS(5),
      /**
       * <code>VIDEO = 6;</code>
       */
      VIDEO(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNIVERSAL = 0;</code>
       */
      public static final int UNIVERSAL_VALUE = 0;
      /**
       * <code>WEB = 1;</code>
       */
      public static final int WEB_VALUE = 1;
      /**
       * <code>IMAGES = 2;</code>
       */
      public static final int IMAGES_VALUE = 2;
      /**
       * <code>LOCAL = 3;</code>
       */
      public static final int LOCAL_VALUE = 3;
      /**
       * <code>NEWS = 4;</code>
       */
      public static final int NEWS_VALUE = 4;
      /**
       * <code>PRODUCTS = 5;</code>
       */
      public static final int PRODUCTS_VALUE = 5;
      /**
       * <code>VIDEO = 6;</code>
       */
      public static final int VIDEO_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Corpus valueOf(int value) {
        return forNumber(value);
      }

      public static Corpus forNumber(int value) {
        switch (value) {
          case 0: return UNIVERSAL;
          case 1: return WEB;
          case 2: return IMAGES;
          case 3: return LOCAL;
          case 4: return NEWS;
          case 5: return PRODUCTS;
          case 6: return VIDEO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Corpus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Corpus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Corpus>() {
              public Corpus findValueByNumber(int number) {
                return Corpus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.nokia.sample.model.DataServer.Data.getDescriptor().getEnumTypes().get(0);
      }

      private static final Corpus[] VALUES = values();

      public static Corpus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Corpus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Data.Corpus)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *required int32 id = 1 [default = 0]; in proto2
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <pre>
     *Unique numbered tag 						//optional string value = 2; in proto2
     * </pre>
     *
     * <code>optional string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Unique numbered tag 						//optional string value = 2; in proto2
     * </pre>
     *
     * <code>optional string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList messageType_;
    /**
     * <code>repeated string messageType = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMessageTypeList() {
      return messageType_;
    }
    /**
     * <code>repeated string messageType = 3;</code>
     */
    public int getMessageTypeCount() {
      return messageType_.size();
    }
    /**
     * <code>repeated string messageType = 3;</code>
     */
    public java.lang.String getMessageType(int index) {
      return messageType_.get(index);
    }
    /**
     * <code>repeated string messageType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageTypeBytes(int index) {
      return messageType_.getByteString(index);
    }

    public static final int CORPUS_FIELD_NUMBER = 4;
    private int corpus_;
    /**
     * <pre>
     *optional Corpus corpus = 4 [default = UNIVERSAL]; in proto2
     * </pre>
     *
     * <code>optional .Data.Corpus corpus = 4;</code>
     */
    public int getCorpusValue() {
      return corpus_;
    }
    /**
     * <pre>
     *optional Corpus corpus = 4 [default = UNIVERSAL]; in proto2
     * </pre>
     *
     * <code>optional .Data.Corpus corpus = 4;</code>
     */
    public com.nokia.sample.model.DataServer.Data.Corpus getCorpus() {
      com.nokia.sample.model.DataServer.Data.Corpus result = com.nokia.sample.model.DataServer.Data.Corpus.valueOf(corpus_);
      return result == null ? com.nokia.sample.model.DataServer.Data.Corpus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      for (int i = 0; i < messageType_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageType_.getRaw(i));
      }
      if (corpus_ != com.nokia.sample.model.DataServer.Data.Corpus.UNIVERSAL.getNumber()) {
        output.writeEnum(4, corpus_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < messageType_.size(); i++) {
          dataSize += computeStringSizeNoTag(messageType_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMessageTypeList().size();
      }
      if (corpus_ != com.nokia.sample.model.DataServer.Data.Corpus.UNIVERSAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, corpus_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nokia.sample.model.DataServer.Data)) {
        return super.equals(obj);
      }
      com.nokia.sample.model.DataServer.Data other = (com.nokia.sample.model.DataServer.Data) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getValue()
          .equals(other.getValue());
      result = result && getMessageTypeList()
          .equals(other.getMessageTypeList());
      result = result && corpus_ == other.corpus_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      if (getMessageTypeCount() > 0) {
        hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageTypeList().hashCode();
      }
      hash = (37 * hash) + CORPUS_FIELD_NUMBER;
      hash = (53 * hash) + corpus_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nokia.sample.model.DataServer.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nokia.sample.model.DataServer.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nokia.sample.model.DataServer.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nokia.sample.model.DataServer.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nokia.sample.model.DataServer.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nokia.sample.model.DataServer.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nokia.sample.model.DataServer.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nokia.sample.model.DataServer.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nokia.sample.model.DataServer.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nokia.sample.model.DataServer.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nokia.sample.model.DataServer.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Data)
        com.nokia.sample.model.DataServer.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nokia.sample.model.DataServer.internal_static_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nokia.sample.model.DataServer.internal_static_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nokia.sample.model.DataServer.Data.class, com.nokia.sample.model.DataServer.Data.Builder.class);
      }

      // Construct using com.nokia.sample.model.DataServer.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        value_ = "";

        messageType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        corpus_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nokia.sample.model.DataServer.internal_static_Data_descriptor;
      }

      public com.nokia.sample.model.DataServer.Data getDefaultInstanceForType() {
        return com.nokia.sample.model.DataServer.Data.getDefaultInstance();
      }

      public com.nokia.sample.model.DataServer.Data build() {
        com.nokia.sample.model.DataServer.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nokia.sample.model.DataServer.Data buildPartial() {
        com.nokia.sample.model.DataServer.Data result = new com.nokia.sample.model.DataServer.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.value_ = value_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          messageType_ = messageType_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.messageType_ = messageType_;
        result.corpus_ = corpus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nokia.sample.model.DataServer.Data) {
          return mergeFrom((com.nokia.sample.model.DataServer.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nokia.sample.model.DataServer.Data other) {
        if (other == com.nokia.sample.model.DataServer.Data.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (!other.messageType_.isEmpty()) {
          if (messageType_.isEmpty()) {
            messageType_ = other.messageType_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMessageTypeIsMutable();
            messageType_.addAll(other.messageType_);
          }
          onChanged();
        }
        if (other.corpus_ != 0) {
          setCorpusValue(other.getCorpusValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nokia.sample.model.DataServer.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nokia.sample.model.DataServer.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       *required int32 id = 1 [default = 0]; in proto2
       * </pre>
       *
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *required int32 id = 1 [default = 0]; in proto2
       * </pre>
       *
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *required int32 id = 1 [default = 0]; in proto2
       * </pre>
       *
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <pre>
       *Unique numbered tag 						//optional string value = 2; in proto2
       * </pre>
       *
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *Unique numbered tag 						//optional string value = 2; in proto2
       * </pre>
       *
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Unique numbered tag 						//optional string value = 2; in proto2
       * </pre>
       *
       * <code>optional string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Unique numbered tag 						//optional string value = 2; in proto2
       * </pre>
       *
       * <code>optional string value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Unique numbered tag 						//optional string value = 2; in proto2
       * </pre>
       *
       * <code>optional string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList messageType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMessageTypeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          messageType_ = new com.google.protobuf.LazyStringArrayList(messageType_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string messageType = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMessageTypeList() {
        return messageType_.getUnmodifiableView();
      }
      /**
       * <code>repeated string messageType = 3;</code>
       */
      public int getMessageTypeCount() {
        return messageType_.size();
      }
      /**
       * <code>repeated string messageType = 3;</code>
       */
      public java.lang.String getMessageType(int index) {
        return messageType_.get(index);
      }
      /**
       * <code>repeated string messageType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes(int index) {
        return messageType_.getByteString(index);
      }
      /**
       * <code>repeated string messageType = 3;</code>
       */
      public Builder setMessageType(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessageTypeIsMutable();
        messageType_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messageType = 3;</code>
       */
      public Builder addMessageType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessageTypeIsMutable();
        messageType_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messageType = 3;</code>
       */
      public Builder addAllMessageType(
          java.lang.Iterable<java.lang.String> values) {
        ensureMessageTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messageType_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messageType = 3;</code>
       */
      public Builder clearMessageType() {
        messageType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messageType = 3;</code>
       */
      public Builder addMessageTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMessageTypeIsMutable();
        messageType_.add(value);
        onChanged();
        return this;
      }

      private int corpus_ = 0;
      /**
       * <pre>
       *optional Corpus corpus = 4 [default = UNIVERSAL]; in proto2
       * </pre>
       *
       * <code>optional .Data.Corpus corpus = 4;</code>
       */
      public int getCorpusValue() {
        return corpus_;
      }
      /**
       * <pre>
       *optional Corpus corpus = 4 [default = UNIVERSAL]; in proto2
       * </pre>
       *
       * <code>optional .Data.Corpus corpus = 4;</code>
       */
      public Builder setCorpusValue(int value) {
        corpus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *optional Corpus corpus = 4 [default = UNIVERSAL]; in proto2
       * </pre>
       *
       * <code>optional .Data.Corpus corpus = 4;</code>
       */
      public com.nokia.sample.model.DataServer.Data.Corpus getCorpus() {
        com.nokia.sample.model.DataServer.Data.Corpus result = com.nokia.sample.model.DataServer.Data.Corpus.valueOf(corpus_);
        return result == null ? com.nokia.sample.model.DataServer.Data.Corpus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *optional Corpus corpus = 4 [default = UNIVERSAL]; in proto2
       * </pre>
       *
       * <code>optional .Data.Corpus corpus = 4;</code>
       */
      public Builder setCorpus(com.nokia.sample.model.DataServer.Data.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        corpus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *optional Corpus corpus = 4 [default = UNIVERSAL]; in proto2
       * </pre>
       *
       * <code>optional .Data.Corpus corpus = 4;</code>
       */
      public Builder clearCorpus() {
        
        corpus_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Data)
    }

    // @@protoc_insertion_point(class_scope:Data)
    private static final com.nokia.sample.model.DataServer.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nokia.sample.model.DataServer.Data();
    }

    public static com.nokia.sample.model.DataServer.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    public com.nokia.sample.model.DataServer.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Data-server.proto\"\260\001\n\004Data\022\n\n\002id\030\001 \001(\005" +
      "\022\r\n\005value\030\002 \001(\t\022\023\n\013messageType\030\003 \003(\t\022\034\n\006" +
      "corpus\030\004 \001(\0162\014.Data.Corpus\"Z\n\006Corpus\022\r\n\t" +
      "UNIVERSAL\020\000\022\007\n\003WEB\020\001\022\n\n\006IMAGES\020\002\022\t\n\005LOCA" +
      "L\020\003\022\010\n\004NEWS\020\004\022\014\n\010PRODUCTS\020\005\022\t\n\005VIDEO\020\006B\030" +
      "\n\026com.nokia.sample.modelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Data_descriptor,
        new java.lang.String[] { "Id", "Value", "MessageType", "Corpus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
